#!/bin/bash

echo "🔍 Debugging DevPod and GitHub Setup on DigitalOcean"
echo ""
echo "Run these commands on your droplet to debug:"
echo ""
echo "# 1. Check if DevPod is installed and configured:"
echo "devpod version"
echo "devpod provider list"
echo ""
echo "# 2. Check Docker status:"
echo "docker info"
echo ""
echo "# 3. Check environment variables in the container:"
echo "docker-compose exec app env | grep -E 'GITHUB|ANTHROPIC'"
echo ""
echo "# 4. Test DevPod manually:"
echo "docker-compose exec app devpod provider add docker"
echo "docker-compose exec app devpod provider use docker"
echo ""
echo "# 5. Check container logs for errors:"
echo "docker-compose logs app | tail -50"
echo ""
echo "# 6. Try creating a test workspace manually:"
echo "docker-compose exec app devpod up https://github.com/devcontainers/templates.git --id test-workspace --provider docker"
echo ""
echo "# 7. Check if the GitHub template repository exists:"
echo "curl -H 'Authorization: token YOUR_GITHUB_TOKEN' https://api.github.com/repos/flexpertsdev/ai-workspace-template"