version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - REACT_APP_API_BASE=http://138.68.141.130:3001
        - REACT_APP_WS_BASE=ws://138.68.141.130:8080
    ports:
      - "80:3000"
      - "3001:3001"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE=http://138.68.141.130:3001
      - REACT_APP_WS_BASE=ws://138.68.141.130:8080
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces:/workspaces
    privileged: true
    restart: unless-stopped