# fly.toml for AI Development Platform

app = "ai-dev-platform"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  NODE_ENV = "production"
  DEVPOD_PROVIDER = "docker"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 3001

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048