# fly.toml app configuration file generated for ai-dev-platform-fly on 2025-06-16T17:40:51+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-dev-platform-fly'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 3001
  protocol = "tcp"
  
  [[services.ports]]
    port = 3001

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    port = 8080

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
