name: Auto Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'project/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd project
        npm install
        
    - name: Build project
      run: |
        cd project
        npm run build
        
    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./project/build
        
    - name: Comment on last commit
      if: success()
      uses: peter-evans/commit-comment@v2
      with:
        body: |
          🚀 **Deployment Successful!**
          
          Your React app has been deployed to GitHub Pages.
          
          View it at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          
          _Deployed from commit ${{ github.sha }}_